import 'widgets/safe_network_image.dart';
import 'widgets/ring_gesture_guide.dart';
import '../l10n/global_locale_controller.dart';
import '../l10n/ui_labels.dart';
import 'global_care_page.dart';
import 'global_auth_page.dart';
import 'global_legal_page.dart';
import 'dart:async';
import 'dart:io';
import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:camera/camera.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:geolocator/geolocator.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart' show DateFormat;
import 'package:package_info_plus/package_info_plus.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:url_launcher/url_launcher.dart';

import '../domain/feature_models.dart';
import '../domain/ecg_waveform.dart';
import '../domain/health_interpretation.dart';
import '../domain/models.dart';
import '../services/app_controller.dart';
import '../services/camera_remote_shutter_gate.dart';
import '../services/device_weather_service.dart';
import '../services/device_watch_face_market_service.dart';
import '../services/health_analysis.dart';
import '../services/say_ring_support.dart';
import 'app_theme.dart';
import 'app_update_gate_scope.dart';
import 'brand_assets.dart';
import 'watch_face_market_page.dart';
import 'sleep_detail_widgets.dart';
import 'health_trend_page.dart';
import '../services/sleep_health_projection.dart';
import 'html_text.dart';

// Compatibility facade: parts retain the existing public API and private helpers.
part 'prototype/legacy_auth.dart';
part 'prototype/health_warning.dart';
part 'prototype/legacy_care.dart';
part 'prototype/health_records.dart';
part 'prototype/device_features.dart';
part 'prototype/device_widgets.dart';
part 'prototype/support.dart';
part 'prototype/legacy_account.dart';
part 'prototype/shared.dart';
