// Reviewed English UI fallback for native-only long copy. Other non-Chinese locales
// use English until a reviewed localized variant exists. Never apply to user/server content.
export const ENGLISH_FALLBACKS: Record<string, string> = {
  "仅在点击开启后申请相机权限。本页面保持打开时，手表拍照键会直接拍摄并保存到手机图库。": "Camera permission is requested only after you choose to start. Keep this page open to take and save photos using your watch.",
  "点击开启后显示实时画面，可在手表相机页面遥控拍照": "Start the live preview, then use the camera page on your watch to take photos.",
  "相机操作已取消": "Camera operation canceled",
  "手机相机尚未准备好，请重新开启相机遥控": "The phone camera is not ready. Turn camera remote off and on again.",
  "已收到手表指令，正在拍照并保存…": "Watch shutter received. Taking and saving your photo…",
  "正在拍照并保存…": "Taking and saving your photo…",
  "照片已保存到手机图库": "Photo saved to your phone's gallery",
  "拍照保存失败，请重试": "Could not save the photo. Please retry.",
  "开启后显示实时取景": "Start to see the live preview",
  "正在保存照片…": "Saving photo…",
  "最近拍摄并保存的照片": "Most recently captured and saved photo",
  "最近拍摄": "Recent photo",
  "已保存到手机图库": "Saved to your phone's gallery",
  "正在拍照…": "Taking photo…",
  "手机拍照": "Take photo",
  "关闭遥控": "Turn off remote",
  "请允许相机权限后使用手表遥控拍照": "Allow camera access to take photos using your watch.",
  "相机正被其他应用使用，请关闭后重试": "Another app is using the camera. Close it and retry.",
  "相机尚未准备好，请稍后重试": "The camera is not ready. Please retry shortly.",
  "相机暂时无法使用，请稍后重试": "The camera is temporarily unavailable. Please retry later.",
  "拍照已取消": "Photo canceled",
  "相机预览区域尚未准备好，请稍后重试": "The camera preview is not ready. Please retry shortly.",
  "当前手机没有可用相机": "No camera is available on this phone.",
  "当前手机不支持标准拍照模式": "This phone does not support the required photo mode.",
  "当前手机没有可用的相机输出规格": "This phone cannot provide a supported photo format.",
  "相机尚未准备好，请先开启相机遥控": "Start camera remote before taking a photo.",
  "拍照保存超时，请重试": "Saving the photo timed out. Please retry.",
  "按需使用": "Used when needed",
  "尚未检查通知状态": "Notification status not checked",
  "尚未连接手表": "No watch connected",
  "点击检查是否有新版本": "Check for a new version",
  "北京": "Beijing",
  "东京": "Tokyo",
  "伦敦": "London",
  "巴黎": "Paris",
  "纽约": "New York",
  "洛杉矶": "Los Angeles",
  "收到新的关爱邀请，可在消息中查看": "A new care invitation is available in Messages.",
  "单位设置暂未读取，请稍后重试": "Could not load units. Please try again.",
  "单位设置未能保存，请重试": "Could not save units. Please try again.",
  "暂时无法读取表盘，请重试": "Could not read watch faces. Please try again.",
  "使用此表盘？": "Use this watch face?",
  "切换后，手表将显示所选表盘。": "The selected watch face will be shown on your watch.",
  "读取手表实际设置": "Read settings from the watch",
  "手表已发出拍照指令": "Camera button received from your watch",
  "点击开启后，可在手表相机页面发送遥控拍照指令": "Turn this on to use your watch's camera button.",
  "暂时无法读取此功能，请重试": "Could not load this feature. Please try again.",
  "保存结果未确认，请重新读取": "Save not confirmed. Read the settings again.",
  "蓝牙通话连接状态已更新": "Call connection status updated",
  "联系人已保存到手表": "Contact saved to the watch",
  "删除联系人？": "Delete this contact?",
  "联系人已从手表删除": "Contact deleted from the watch",
  "天气设置已保存到手表": "Weather settings saved to the watch",
  "删除世界时钟？": "Delete this world clock?",
  "屏幕显示设置已保存到手表": "Display settings saved to the watch",
  "相机遥控已开启，请在手表上点击拍照": "Remote camera is on. Tap the camera button on your watch.",
  "相机遥控已关闭": "Remote camera is off",
  "相机遥控已开启": "Remote camera is on",
  "照片已选择，请确认后安装到手表": "Photo selected. Confirm to install it on your watch.",
  "无法读取照片，请重新选择": "Could not read this photo. Please choose another.",
  "请先选择一张照片": "Choose a photo first.",
  "照片表盘已安装到手表": "Photo watch face installed",
  "确定删除这个闹钟吗？": "Delete this alarm?",
  "闹钟已删除": "Alarm deleted",
  "闹钟已保存": "Alarm saved",
  "个人资料已保存": "Profile saved",
  "登录已失效，请重新登录": "Your session expired. Please sign in again.",
  "反馈已提交，感谢你的建议": "Feedback submitted. Thank you.",
  "操作未完成，请稍后重试": "Could not complete this action. Please try again later.",
  "地区暂时无法读取，请重新进入此页面": "Could not load regions. Reopen this page to try again.",
  "部分消息暂未更新，请稍后重试": "Some messages could not be updated. Please try again later.",
  "消息已读状态暂未保存，请稍后重试": "Could not save the read status. Please try again later.",
  "暂时无法读取权限状态，请重试": "Could not check permissions. Please try again.",
  "请在手机设置中查看赛电的应用权限": "View Saydian permissions in your phone settings.",
  "运动记录读取失败，请重试": "Could not read workout records. Please try again.",
  "同步未完成，已保存的记录仍可查看": "Sync did not finish. Saved records are still available.",
  "当前手表未能开始运动": "The watch could not start the workout.",
  "手表未确认运动状态，请稍后重试": "The watch has not confirmed the workout status. Please try again.",
  "结束本次运动？": "End this workout?",
  "结束后将保存手表返回的数据和已记录的前台轨迹。": "Ending saves the data returned by your watch and the route recorded by your phone.",
  "手表未确认结束运动": "The watch has not confirmed the end of the workout.",
  "设备不支持": "Not supported by this watch",
  "收缩压": "Systolic",
  "舒张压": "Diastolic",
  "尚未同步健康数据": "No health data synced yet",
  "等待手表读数": "Waiting for watch readings",
  "请先登录赛电账号，再开启消息推送": "Sign in before enabling notifications.",
  "正在检查系统通知与推送身份…": "Checking notification service…",
  "系统通知未开启；打开 App 时仍可收到邀请提醒": "System notifications are off. Invitations are still visible while using the app.",
  "通知服务已开启": "Notifications enabled",
  "通知服务暂时不可用，请稍后重试": "Notification service is unavailable. Please try again later.",
  "已退出账号，推送标识已从本机清除": "Signed out. Notification registration cleared on this phone.",
  "请先登录赛电账号，再查看关爱邀请和健康预警。": "Sign in to view care invitations and health alerts.",
  "请先登录赛电账号，再查看订单与支付状态。": "Sign in to view orders and payment status.",
  "商城暂时无法加载": "The shop could not be loaded.",
  "该商品暂无可购买规格": "This product has no available options.",
  "请先登录后购买": "Sign in before purchasing.",
  "购物车": "Cart",
  "请先登录后查看购物车": "Sign in to view your cart.",
  "移出购物车？": "Remove this item from your cart?",
  "订单已生成，购物车请稍后刷新确认": "Order created. Refresh the cart to confirm its contents.",
  "确认已经收到商品？": "Have you received your order?",
  "确认收货后订单将完成。如尚未收到商品，请不要确认。": "Confirming completes the order. Only confirm if you have received the items.",
  "请检查申请金额和售后原因": "Check the requested amount and reason.",
  "申请结果请以最新订单状态为准": "Check the latest order status for the result.",
  "AI 健康管家": "AI wellness assistant",
  "请先登录赛电账号，再向 AI 健康管家提问。": "Sign in to ask the AI wellness assistant a question.",
  "，需要更新后继续使用": ". Update to continue.",
  "无法打开华为应用市场，请稍后重试": "Could not open the update page. Please try again.",
  "订单状态已更新，无需重复支付": "Order status updated. Do not pay again.",
  "订单状态暂时无法刷新": "Could not refresh order status.",
  "请先安装微信后再支付": "Install WeChat to use this payment method.",
  "当前手机暂时无法使用支付宝支付": "Alipay is unavailable on this phone.",
  "支付流程已返回": "Returned from payment",
  "支付客户端响应超时，已停止等待": "Payment timed out. Check the order status before trying again.",
  "订单仍待支付，请确认支付结果或稍后刷新": "Payment is still pending. Check the result or refresh later.",
  "支付流程已结束": "Payment flow ended",
  "关爱服务暂不可用，请稍后重试": "Care services are unavailable. Please try again later.",
  "读取失败，请稍后重试": "Could not load this information. Please try again later.",
  "请先登录赛电账号，再查看成员与共享授权。": "Sign in to view care members and sharing permissions.",
  "邀请已提交，请等待对方同意并选择共享项目。": "Invitation sent. The recipient must accept and choose what to share.",
  "已同意邀请。请到共享管理选择允许对方查看的项目。": "Invitation accepted. Choose what to share in Sharing settings.",
  "已拒绝邀请。": "Invitation declined.",
  "已保存并重新读取共享设置。": "Sharing settings saved and checked.",
  "不能查看未来日期": "Future dates cannot be selected.",
  "请先阅读并同意用户协议与隐私政策": "Read and agree to the Terms and Privacy Policy first.",
  "微信登录失败，请重试": "WeChat sign-in failed. Please try again.",
  "微信登录暂时不可用，请使用手机号登录": "WeChat sign-in is unavailable. Use your email or phone number.",
  "内容暂不可用，请稍后重试": "Content is unavailable. Please try again later.",
  "请重新读取最新设备设置": "Read the latest watch settings again.",
  "赛电商城": "Saydian shop",
  "支付收银台": "Payment",
  "关爱邀请": "Care invitations",
  "共享管理": "Sharing settings",
  "共享数据管理": "Data sharing",
  "添加关爱成员": "Add care member",
  "成员健康数据": "Member health data",
  "手机号或账号": "Email or phone number",
  "同意用户协议与隐私政策": "Agree to the Terms and Privacy Policy",
  "重试清除本机登录状态": "Retry signing out on this phone",
  "正在打开微信…": "Opening WeChat…",
  "微信授权登录": "Sign in with WeChat",
  "使用微信授权登录": "Use WeChat to sign in",
  "赛电 SAYDIAN": "Saydian",
  "赛电": "Saydian",
  "赛电健康管家形象": "Saydian wellness assistant",
  "我是您的健康管家，\\n有任何健康问题都可以向我提问。": "Ask me a question about your wellbeing.",
  "查看已保存的运动记录": "View saved workouts",
  "设备标识暂不可用": "Device identifier unavailable",
  "查看并切换手表内表盘": "View and switch watch faces",
  "选择照片并按手表尺寸制作": "Choose a photo for your watch face",
  "1. 打开手机蓝牙并允许查找附近设备。\\n2. 让手表保持亮屏并靠近手机。\\n3. 如果手表弹出确认，请及时确认。": "1. Turn on Bluetooth and allow nearby-device access.\n2. Keep the watch screen on and near your phone.\n3. Confirm on your watch if prompted.",
  "手表保持亮屏、靠近手机，并确认未被其他手机占用": "Keep the watch screen on and near your phone. Disconnect it from other phones first.",
  "1. 打开手机蓝牙并允许查找附近设备。\\n2. 将手表充电激活并靠近手机。\\n3. 点击“开始查找”选择自己的手表。": "1. Turn on Bluetooth and allow nearby-device access.\n2. Charge your watch and place it near your phone.\n3. Tap Find devices and choose your watch.",
  "当前使用": "In use",
  "预览\\n暂不可用": "Preview unavailable",
  "手表已断开": "Watch disconnected",
  "连接手表后可查看和切换表盘。": "Connect your watch to view and switch watch faces.",
  "当前手表不支持此功能": "This watch does not support this feature.",
  "可切换手表内已有表盘": "Switch among the watch faces already on your watch",
  "请让手表靠近手机后重新读取。": "Keep the watch near your phone and read again.",
  "重新连接后再查看或调整此功能。": "Reconnect your watch to view or change this feature.",
  "设备页只会展示手表能力表中已支持的功能。": "Only features supported by the connected watch are shown.",
  "无法": "Unavailable",
  "已选择的照片表盘预览": "Selected photo watch face preview",
  "请重新读取后再试。": "Read the settings again, then retry.",
  "相机遥控会让手表进入拍照控制状态。本页面保持打开时，可接收手表的拍照按键事件。": "Remote camera enables your watch's camera button. Keep this page open to receive button presses.",
  "相机遥控尚未开启": "Remote camera is not on",
  "关闭相机遥控": "Turn off remote camera",
  "蓝牙通话已连接": "Watch calls connected",
  "蓝牙通话未连接": "Watch calls not connected",
  "连接手表通话蓝牙": "Connect watch calls",
  "手表中还没有联系人": "No contacts on the watch",
  "当前 SOS": "Current SOS contact",
  "手表没有返回可配置的消息类型": "No notification options were returned by the watch.",
  "开启后同步天气信息到手表": "Enable to sync weather to your watch",
  "手表中还没有世界时钟": "No world clocks on the watch",
  "手表没有返回可配置的健康提醒": "No configurable wellness reminders were returned by the watch.",
  "监测间隔按手表支持的最小步长调整，保存后会重新读取确认。": "Intervals follow the options supported by your watch. Settings are read again after saving.",
  "手表没有返回可配置的自动监测项目": "No automatic monitoring options were returned by the watch.",
  "全天按手表规则监测": "Monitor throughout the day using the watch's settings",
  "手表没有返回可配置的辅助评估": "No configurable assessment options were returned by the watch.",
  "当前手表没有可调整的屏幕项目": "No adjustable display options on this watch.",
  "重新连接后查看设备设置。": "Reconnect to view watch settings.",
  "其他设置可在手表上查看和调整。": "Other settings can be viewed and changed on your watch.",
  "，当前使用": ", in use",
  "重新连接后再查看或调整。": "Reconnect to view or change settings.",
  "当前手表不支持闹钟管理": "This watch does not support alarm management.",
  "当前手表没有可调整的单位": "No adjustable units on this watch.",
  "此处修改手表显示单位，不改变已有健康记录。": "Changes the watch's display units without changing existing health records.",
  "手表中还没有闹钟": "No alarms on the watch",
  "返回闹钟列表重新读取": "Return to the alarm list and read again",
  "，已选择": ", selected",
  "，未选择": ", not selected",
  "让手表保持亮屏并靠近手机": "Keep the watch screen on and near your phone.",
  "打开手表配对页，并确认未被其他手机占用": "Open the watch's pairing page and disconnect it from other phones.",
  "没有设备？去赛电商城看看": "Need a watch? Visit the Saydian shop.",
  "前往赛电商城": "Open Saydian shop",
  "赛电头像": "Saydian profile picture",
  "登录赛电账号": "Sign in to Saydian",
  "当前页": "Current page",
  "点击指标查看详情与历史趋势": "Tap a metric for details and history.",
  "数值仅供健康管理参考，不自动判断疾病或异常。": "Values are for wellness reference only. They do not establish a diagnosis.",
  "连接手表后可开始运动和同步记录，已有记录仍可离线查看。": "Connect your watch to start workouts and sync records. Saved records remain available offline.",
  "当前手表不支持同步运动记录，已有记录仍可查看。": "This watch does not support workout sync. Existing records remain available.",
  "当前手表支持运动历史，但未开放由 App 开始运动；可直接在手表上开始。": "This watch supports workout history. Start workouts directly on the watch.",
  "完成一次运动或连接手表同步后，可在这里查看。": "Complete a workout or sync your watch to see records here.",
  "健康预警仅作健康管理提醒": "Health alerts are wellness reminders only.",
  "如有不适，请及时咨询专业医务人员。这里只展示已收到的健康预警。": "If you feel unwell, seek medical advice. Only alerts already received are shown here.",
  "当前暂无商品": "No products available",
  "赛电商城横幅": "Saydian shop banner",
  "当前分类暂无商品": "No products in this category",
  "小计 ": "Subtotal ",
  "购物车还是空的": "Your cart is empty",
  "去商城挑选适合您的健康设备吧": "Browse the shop to find a watch.",
  "请先核对我的订单，避免重复提交。": "Check My orders before submitting again.",
  "请选择需要售后的商品，并填写原因和申请金额。提交后可在订单列表查看处理状态。": "Select the item, explain the issue and enter the requested amount. Check the order list for updates.",
  "该商品已经提交售后申请，请等待商城工作人员处理。": "A request has already been submitted for this item. Please wait for support to review it.",
  "仅退款": "Refund only",
  "您好，我是 AI 健康管家": "Hello, I am your AI wellness assistant.",
  "可以向我咨询日常健康管理问题，回答仅供参考，不能替代医生诊断。": "Ask about everyday wellbeing. Answers are for reference and do not replace medical advice.",
  "发送失败，请检查网络后重试": "Could not send. Check your connection and retry.",
  "AI 正在思考，请耐心等待…": "The AI assistant is preparing a reply…",
  "登录后可管理账号信息。": "Sign in to manage account information.",
  "查看账号中的收货地址": "View saved delivery addresses",
  "验证手机号后重新设置登录密码": "Verify your email or phone number to reset your password.",
  "已选择新头像，保存后生效": "New photo selected. Save to apply it.",
  "点击头像更换照片": "Tap your profile picture to change it.",
  "保存后，资料会同步到当前账号。": "Saving updates the profile for the current account.",
  "单位设置会影响 App 内的数据显示，不会更改原始记录。": "Units change how values are displayed in the app, not the original records.",
  "赛电健康": "Saydian",
  "让健康数据更直观，让日常管理更轻松。": "Understand your wellness data and manage your daily routines.",
  "测量结果仅供健康管理参考，不用于诊断或治疗。": "Measurements are for wellness reference, not diagnosis or treatment.",
  "如何连接手表？": "How do I connect my watch?",
  "为什么健康数据暂时为空？": "Why is my health data empty?",
  "打开蓝牙，让手表靠近手机，进入“设备”添加手表。若已连接其他手机，请先断开后重试。": "Turn on Bluetooth, place your watch near the phone and add it from Device. Disconnect it from other phones before retrying.",
  "连接手表并同步数据后，再选择有记录的日期查看。设备不支持的项目不会显示。": "Connect and sync your watch, then select a date with records. Unsupported metrics are not shown.",
  "仅在使用对应功能时申请权限。锁屏通知不显示具体健康数值。": "Permissions are requested only when needed. Lock-screen notifications do not show health values.",
  "微信支付": "WeChat Pay",
  "使用微信安全支付": "Pay with WeChat",
  "支付宝支付": "Alipay",
  "使用支付宝安全支付": "Pay with Alipay",
  "该时间段暂无数据": "No data in this period",
  "深睡": "Deep sleep",
  "浅睡": "Light sleep",
  "清醒": "Awake",
  "触摸图表查看记录": "Touch the chart to view records.",
  "按日汇总 · 触摸查看记录": "Daily summary · Touch to view records",
  "趋势仅作日常健康参考": "Trends are for wellness reference only.",
  "单次和阶段变化可能受佩戴、运动及环境影响，不替代医疗诊断。": "Readings and trends can be affected by fit, activity and surroundings. They do not replace medical assessment.",
  "来源：手表历史": "Source: watch history",
  "来源：App 运动": "Source: app workout",
  "来源：App 测量": "Source: app measurement",
  "该记录没有手机前台轨迹，仍保留手表运动数据。": "No phone route was recorded. Watch workout data is still available.",
  "逐段查看完整心电波形": "View the full ECG waveform by segment",
  "记录暂不可用": "Record unavailable",
  "当日摘要": "Daily summary",
  "仅汇总所选日期的有效记录": "Includes valid records for the selected date only.",
  "本条记录未包含可用心电波形": "This record does not contain an available ECG waveform.",
  "来源：关爱成员授权共享": "Source: shared with the care member's permission",
  "守护家人健康": "Care for your family",
  "添加关爱成员后查看授权数据": "Add a care member to view data they choose to share.",
  "授权与隐私": "Permissions and privacy",
  "通过手机号邀请家人，对方接受并授权后才会共享健康数据。": "Invite a family member by phone number. Health data is shared only after they accept and grant permission.",
  "查看已授权的健康记录": "View permitted health records",
  "默认不共享任何数据；成员可按指标授权并随时撤销。": "No data is shared by default. Members choose the metrics to share and can withdraw permission.",
  "邀请只向您填写的账号发送。对方接受后，还需要主动选择共享项目。": "The invitation is sent only to the account you enter. The recipient must accept and choose what to share.",
  "请输入家人手机号": "Enter your family member's phone number",
  "发送关爱邀请": "Send care invitation",
  "收到家人的关爱请求后，会显示在这里。": "Care invitations from your family appear here.",
  "请确认邀请人后再接受": "Check who sent the invitation before accepting.",
  "同意邀请不会自动开启健康数据共享。": "Accepting an invitation does not automatically share health data.",
  "这里管理哪些关爱人可以查看您的数据。只显示您已经同意的邀请。": "Manage who can view your data. Only accepted invitations are shown.",
  "同意关爱邀请后，可在这里管理共享项目。": "After accepting an invitation, manage shared metrics here.",
  "只有已开启的项目会共享；关闭后保存即可撤销。": "Only enabled metrics are shared. Turn them off and save to withdraw permission.",
  "共享设置暂时不可用": "Sharing settings are unavailable.",
  "当前不会更改任何授权项目。": "No sharing permissions will be changed.",
  "其他已有共享设置将保持不变。": "Other existing sharing settings remain unchanged.",
  "保存共享设置": "Save sharing settings",
  "对方未授权此项目": "This metric has not been shared.",
  "当日暂无记录": "No records for this day",
  "服务暂不可用，可刷新重试": "Service unavailable. Refresh to retry.",
  " 条记录": " records",
  "查看完整心电波形": "View full ECG waveform",
  "健康百科加载失败": "Could not load the health library",
  "该分类暂无百科内容": "No articles in this category",
  "配图暂不可用。": "Image unavailable.",
  "请输入消息…": "Enter a message…"
};
